"use server";

import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";

const studentSchema = z.object({
  FirstName: z.string().min(2, {
    message: "First name must be at least 2 characters.",
  }),
  LastName: z.string().min(2, {
    message: "Last name must be at least 2 characters.",
  }),
  DateOfBirth: z.string(),
  Gender: z.string(),
  ParentContact: z.string().min(10, {
    message: "Phone number must be at least 10 digits.",
  }),
  Address: z.string(),
  StudentClassID: z.string(),
});

export async function addStudent(values: z.infer<typeof studentSchema>) {
  const validatedFields = studentSchema.safeParse(values);

  if (!validatedFields.success) {
    return {
      success: false,
      message: "Invalid data provided.",
      errors: validatedFields.error.flatten().fieldErrors,
    };
  }

  try {
    // Verify that the class exists
    const classExists = await prisma.class.findUnique({
      where: { ClassID: validatedFields.data.StudentClassID }
    });

    if (!classExists) {
      return {
        success: false,
        message: "Selected class does not exist. Please choose a valid class.",
      };
    }

    const student = await prisma.student.create({
      data: {
        FirstName: validatedFields.data.FirstName,
        LastName: validatedFields.data.LastName,
        DateOfBirth: new Date(validatedFields.data.DateOfBirth),
        Gender: validatedFields.data.Gender,
        ParentContact: validatedFields.data.ParentContact,
        Address: validatedFields.data.Address,
        StudentClassID: validatedFields.data.StudentClassID,
        // AdmissionNumber will be auto-generated by Prisma
      },
      include: { Class: true }
    });

    revalidatePath("/students");

    return {
      success: true,
      message: "Student created successfully.",
      student,
    };
  } catch (error) {
    console.error("Add student error:", error);
    
    // Check for foreign key constraint error
    if (error instanceof Error && error.message.includes('foreign key constraint')) {
      return {
        success: false,
        message: "Invalid class selected. Please choose a valid class from the dropdown.",
      };
    }
    
    return {
      success: false,
      message: "Failed to create student. Please try again.",
    };
  }
}

export async function updateStudent(
  admissionNumber: string,
  values: z.infer<typeof studentSchema>
) {
  const validatedFields = studentSchema.safeParse(values);

  if (!validatedFields.success) {
    return {
      success: false,
      message: "Invalid data provided.",
    };
  }

  try {
    await prisma.student.update({
      where: { AdmissionNumber: admissionNumber },
      data: {
        ...validatedFields.data,
        DateOfBirth: new Date(validatedFields.data.DateOfBirth),
      },
    });

    revalidatePath("/students");

    return {
      success: true,      message: "Student updated successfully.",
    };
  } catch {
    return {
      success: false,
      message: "Failed to update student.",
    };
  }
}

export async function deleteStudent(admissionNumber: string) {
  try {
    await prisma.student.delete({
      where: { AdmissionNumber: admissionNumber },
    });

    revalidatePath("/students");

    return {
      success: true,
      message: "Student deleted successfully.",    };
  } catch {
    return {
      success: false,
      message: "Failed to delete student.",
    };
  }
}
